Log:
  Level: info # Log level: none, error, warning, info, debug 
  AccessPath: # /etc/XMPlus/access.Log
  ErrorPath: # /etc/XMPlus/error.log
DnsConfigPath:  /etc/XMPlus/dns.json
RouteConfigPath: # /etc/XMPlus/route.json
InboundConfigPath: # /etc/XMPlus/inbound.json
OutboundConfigPath: # /etc/XMPlus/outbound.json
ConnectionConfig:
  Handshake: 8 
  ConnIdle: 300 
  UplinkOnly: 0 
  DownlinkOnly: 0 
  BufferSize: 64
Nodes:
  -
    ApiConfig:
      ApiHost: "https://xmplus.dev"
      ApiKey: "123"
      NodeID: 1
      Timeout: 30 
    ControllerConfig:
      UpdatePeriodic: 120
      CertConfig:
        Email: author@xmplus.dev                    # Required when Cert Mode is not none
        CertFile: /etc/XMPlus/node1.xmplus.dev.crt  # Required when Cert Mode is file
        KeyFile: /etc/XMPlus/node1.xmplus.dev.key   # Required when Cert Mode is file
        Provider: cloudflare                        # Required when Cert Mode is dns
        CertEnv:                                    # Required when Cert Mode is dns
          CLOUDFLARE_EMAIL:                         # Required when Cert Mode is dns
          CLOUDFLARE_API_KEY:                       # Required when Cert Mode is dns
          
#  -
#    ApiConfig:
#      ApiHost: "https://xmplus.dev"
#      ApiKey: "123"
#      NodeID: 2
#      Timeout: 30 
#    ControllerConfig:
#      UpdatePeriodic: 120
#      CertConfig:
#        Email: author@xmplus.dev                    # Required when Cert Mode is not none
#        CertFile: /etc/XMPlus/node1.xmplus.dev.crt  # Required when Cert Mode is file
#        KeyFile: /etc/XMPlus/node1.xmplus.dev.key   # Required when Cert Mode is file
#        Provider: cloudflare                        # Required when Cert Mode is dns
#        CertEnv:                                    # Required when Cert Mode is dns
#          CLOUDFLARE_EMAIL:                         # Required when Cert Mode is dns
#          CLOUDFLARE_API_KEY:                       # Required when Cert Mode is dns